### ISSUE TITLE
Upgrade heroku-bouncer before 4/15/17

### ISSUE THREAD

**Issue by dmcinnes** [heroku/pgperf#17]
Just as a reminder: earlier this year we've announced that API v2 is being sunset on April 15, 2017:
https://devcenter.heroku.com/changelog-items/862

The version of heroku-bouncer that this repo uses runs off of a deprecated v2 API endpoint. Please upgrade to at least 0.7.0 where usage was moved to v3.

Thanks!

**Comment by cyberdelia** [comment]
We're going
